create table
  public.potions (
    id integer generated by default as identity,
    quantity integer null default 0,
    potion_type integer[] null,
    sku text null,
    price integer null,
    name text null,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    cart_id bigint null,
    potions_id integer null,
    quantity integer null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_potions_id_fkey foreign key (potions_id) references potions (id)
  ) tablespace pg_default;